### ISSUE TITLE
when installing via haxelib install, there is a minor folder hierarchy bug

### ISSUE THREAD

**Issue by scarletsquig** [CreativeMagic/Screen-Manager#1]
Basically, when you try to use this library and it installs, flashdevelop looks for com.creativemage.screenManager.

The actual filepath in the folder is Source/com/creativemage/screenManager

So, all that needs to be done is cutting the com folder out and pasting it a level higher, into the 0,9,0 folder where the .current file tells haxe to look for it.

Anyway, very minor bug, looking forward to using these classes to build a robust UI template for my games!

**Comment by CreativeMagic** [comment]
Thanks for the bug report! I'll definitely fix that and add new features and a better screen transition algorithm for those performance-heave screens.

**Comment by CreativeMagic** [comment]
Path is corrected. Thank you again for pointing that out.
