### ISSUE TITLE
Basic documentation, example of usage?

### ISSUE THREAD

**Issue by scarletsquig** [CreativeMagic/Screen-Manager#2]
Trying to make use of what looks like an excellent screen manager, but having difficulty deciphering the manner in which it was intended to be used, with no code comments, documentation or example usage listed, I'm resorting to fumbling around in the dark, here's what I have so far, and it doesn't work, throwing null object reference errors (MainMenu is correctly extending the AScreen class):

import com.creativemage.screenManager.*;

class Main extends Sprite {
	
	public function new () {
		
		super ();
		var screen_list = new AScreenList();
		screen_list.push("main_menu", MainMenu);
		var screen_manager = new ScreenManager(this, 800, 470, screen_list);
		screen_manager.addScreenClass(MainMenu, "main_menu");
		screen_manager.gotoScreenByName("main_menu");
		
	}

Are there any plans to update this haxelib or add usage examples to it?

**Comment by CreativeMagic** [comment]
Sorry for a very late response.
Yes, the library will be updated soon. Samples, bug fixes and some quality of life changes. I'm planning to implement those within the upcoming week.

**Comment by CreativeMagic** [comment]
Samples are now added. I will add more samples if there will be requests for more.
